export default {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_RESPONSE: 'GET_ALL_USERS_RESPONSE',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',


    GET_USER_BY_ID: 'GET_USER_BY_ID',
    GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
    GET_USER_BY_ID_RESPONSE: 'GET_USER_BY_ID_RESPONSE',
    GET_USER_BY_ID_ERROR: 'GET_USER_BY_ID_ERROR',


    CREATE_USER: 'CREATE_USER',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_RESPONSE: 'CREATE_USER_RESPONSE',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',


    GET_CURRENT_USER: 'GET_CURRENT_USER',

    LOGIN: 'LOGIN',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',
    LOGIN_ERROR: 'LOGIN_ERROR',


    RESET: 'RESET',
    UPDATE_EVENT: 'UPDATE_EVENT',

}

//we use it in REDUCER, ACTION_CREATOR, SAGAS